---
# tasks file for haproxy

- name: "Configure haproxy load balancer"
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Haproxy"
