---
# file: shib-idp-idm-servers.yml
- hosts: Debian_IdP_with_IdM
  become: yes
  become_method: sudo
  remote_user: debian
  roles:
    - common
    - apache
    - jdk
    - jetty
    - openldap
    - mysql
    - idp
    - phpldapadmin
    - sys-update
  serial: 3
