---
# file: shib-idp-servers.yml
- hosts: Debian_IdP_without_IdM
  become: yes
  become_method: sudo
  remote_user: debian
  roles:
    - common
    - apache
    - jdk
    - jetty
    - mysql
    - idp
    - check_mk_agent
    - sys-update
  serial: 3
