---
# file: shib-idp-idm-servers-garr.yml
- hosts: Debian-IdP-with-IdM-GARR
  become: yes
  become_method: sudo
  remote_user: debian
  roles:
    - common
    - apache
    - jdk
    - jetty
    - openldap
    - flup
    - mysql
    - idp
    - phpldapadmin
    - idpcloud_garr
    - geant-fticks
    - check_mk_agent
    - rsync
    - sys-update
  serial: 3
