---
# defaults file for jdk
# Available:
#
# OpenJDK: 
#   jdk_type: "openjdk"
#   jdk_version: "11"
#
# Amazon Corretto JDK: 
#   jdk_type: "corretto"
#   jdk_version: "11"

jdk_type: "corretto"
jdk_version: "11"
