---
# Task for backup.yml
- name: "Look for mysql-backup script"
  stat:
    path: "/ect/cron.hourly/mysql-backup"
  register: mysqlbackup

- name: "Force a backup of the IdP mysql"
  shell: "/etc/cron.hourly/mysql-backup"
  when: mysqlbackup.stat.exists is defined

- name: "Look for ldap-backup script"
  stat:
    path: "/ect/cron.hourly/ldap-backup"
  register: ldapbackup
  
- name: "Force a backup of the IdP slapd"
  shell: "/etc/cron.hourly/ldap-backup"
  when: 
   - ldapbackup.stat.exists is defined
   - ldapbackup.stat.exists == True
