---
# handlers file for check_mk

- name: "Activate changes on Check_MK centralized server"
  uri:
   url: "https://{{ check_mk['srv'] }}/{{ check_mk['site'] }}/check_mk/webapi.py?action=activate_changes&_username={{ check_mk['api_user_name'] }}&_secret={{ check_mk['api_user_secret'] }}"
   method: GET 
   status_code: 200
   timeout: 300
   headers:
     Content-Type: "application/json; charset=UTF-8"
  delegate_to: 127.0.0.1

- name: "Add probes to Check_MK centralized server"
  uri:
   url: "https://{{ check_mk['srv'] }}/{{ check_mk['site'] }}/check_mk/webapi.py?action=discover_services&_username={{ check_mk['api_user_name'] }}&_secret={{ check_mk['api_user_secret'] }}&mode=new&hostname={{ fqdn }}"
   method: GET
   timeout: 300
   status_code: 200
  delegate_to: 127.0.0.1
  notify:
   - "Activate changes on Check_MK centralized server"

- name: "Remove probes from Check_MK centralized server"
  uri:
   url: "https://{{ check_mk['srv'] }}/{{ check_mk['site'] }}/check_mk/webapi.py?action=discover_services&_username={{ check_mk['api_user_name'] }}&_secret={{ check_mk['api_user_secret'] }}&mode=remove&hostname={{ fqdn }}"
   method: GET
   timeout: 300
   status_code: 200
  delegate_to: 127.0.0.1
  notify:
   - "Activate changes on Check_MK centralized server"
