---
# Debian Variables for Check_MK

check_mk_agent_packages:
 - wget
 - gdebi
 - xinetd

check_mk_agent_pkg: "check-mk-agent_1.6.0p25-1_all.deb"

check_mk_agent_dl_url: "https://{{ check_mk['srv'] }}/{{ check_mk['site'] }}/check_mk/agents/{{ check_mk_agent_pkg }}"
