---
# Tasks file for idp-install
- name: "Check if Shibboleth IdP directory exists"
  stat:
   path: "/opt/shibboleth-idp"
  register: shib_idp_dir
  changed_when: false

- name: "Check if Shibboleth IdP tarball exists" 
  stat: 
   path: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}.tar.gz"
  register: shib_tarball

- name: "Download Shibboleth IdP and check its SHA256 checksum"
  get_url:
   url: "{{ idp_dl_url }}"
   dest: "/usr/local/src"
   checksum: "sha256:{{ shib_idp_checksum }}"
  when:
   - shib_tarball.stat.exists == False

- name: "Extract Shibboleth Identity Provider package"
  unarchive:
   src: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}.tar.gz"
   dest: "/usr/local/src"
   owner: "root"
   group: "root"
   remote_src: yes
  when:
   - shib_tarball.stat.exists == False

- name: "Put Shibboleth Identity Provider v4.x installer properties' files in the right position"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "installer-v4.properties.j2", dest: "/tmp/installer.properties", mode: "0644" } 
  when: 
   - shib_tarball.stat.exists == False
   - "shib_idp_version is search('^4.')"

- name: "Put the Shibboleth Identity Provider persistent-id database structure file in the right position"
  template:
   src: "shib-idp-persistentId-db.sql.j2"
   dest: "/root/shib-idp-persistentId-db.sql"
   owner: "root"
   group: "root"
   mode: "0600"
  when:
   - idp_config is defined
   - idp_config['idp_persistentId_type'] is defined
   - idp_config['idp_persistentId_type'] == "stored"

- name: "Create link for commons-dbcp & commons-pool JAR files needed by Shibboleth IdP for 'stored' persistent-id"
  file:
   src: "{{ item.src }}" 
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "jetty"
   state: link
  with_items:
   - { src: '/usr/share/java/commons-dbcp.jar' ,dest: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}/webapp/WEB-INF/lib/commons-dbcp.jar" }
   - { src: '/usr/share/java/commons-pool.jar' ,dest: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}/webapp/WEB-INF/lib/commons-pool.jar" }
  when:
   - idp_config is defined
   - idp_config['idp_persistentId_type'] is defined
   - idp_config['idp_persistentId_type'] == "stored"

- name: "Create link for MariaDB Connector JAR files needed by Shibboleth IdP for 'stored' persistent-id"
  file:
   src: "{{ item.src }}" 
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "jetty"
   state: link
  with_items:
   - { src: '/usr/share/java/mariadb-java-client.jar', dest: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}/webapp/WEB-INF/lib/mariadb-java-client.jar" }
  when: 
   - idp_config is defined
   - idp_config['idp_persistentId_type'] is defined
   - idp_config['idp_persistentId_type'] == "stored"

- name: "Install Shibboleth IdP"
  shell: "./install.sh -Didp.property.file=/tmp/installer.properties"
  args:
    chdir: "/usr/local/src/shibboleth-identity-provider-{{ shib_idp_version }}/bin"
  environment:
    JAVA_HOME: "{{ java_home_dir }}"
  when:
   - shib_tarball.stat.exists == False
  notify:
   - "Restart Jetty"

- name: "Set right permissions to Shibboleth IdP directories"
  file:
   path: "/opt/shibboleth-idp/{{ item }}"
   owner: "jetty"
   recurse: "yes"
   state: directory
  with_items:
    - "logs"
    - "metadata"
    - "credentials"
    - "conf"
    - "war"
