---
# tasks file for jetty

- name: "Include jetty default variables"
  include_vars:
    file: "java{{ jdk_version }}_jetty_vars.yml"
  when: jetty_distribution is undefined or jetty_distribution == ""
  tags: jetty 

- name: "Create 'jetty' group"
  group: 
   name: "jetty"
   state: present
  tags: jetty

- name: "Create 'jetty' user"
  user: 
   name: "jetty"
   groups: "jetty"
   createhome: "no"
  tags: jetty

- name: "Extract Jetty Package"
  unarchive:
   src: "files/{{ ansible_os_family }}/java{{ jdk_version }}/{{ jetty_distribution }}.tar.gz"
   dest: "/usr/local/src"
   owner: "jetty"
   group: "jetty"
  tags: jetty

- name: "Create 'jetty-src' link"
  file:
   src: "{{ item.src }}" 
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "jetty"
   state: link
  with_items:
   - { src: '/usr/local/src/{{ jetty_distribution }}' , dest: '/usr/local/src/jetty-src' }
  register: jetty_src
  tags: jetty

- name: "Create '/etc/init.d/jetty' link"
  file:
   src: "{{ item.src }}" 
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "jetty"
   state: link
  with_items:
   - { src: '/usr/local/src/jetty-src/bin/jetty.sh' , dest: '/etc/init.d/jetty' }
  tags: jetty

- name: "Create Jetty's directories"
  file:
   path: "{{ item }}"
   owner: "jetty"
   group: "jetty"
   state: directory
  with_items:
   - /opt/jetty
   - /opt/jetty/etc
   - /opt/jetty/lib
   - /opt/jetty/lib/ext
   - /opt/jetty/logs
   - /opt/jetty/resources
   - /opt/jetty/webapps
   - /opt/jetty/tmp
   - /var/log/jetty
  tags: jetty
  
- name: "Configure Jetty"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "jetty"
  with_items:
   - { src: "files/{{ ansible_os_family }}/java{{ jdk_version }}/jetty", dest: '/etc/default/jetty' }
   - { src: "files/{{ ansible_os_family }}/java{{ jdk_version }}/start.ini", dest: '/opt/jetty/start.ini' }
   - { src: "files/{{ ansible_os_family }}/java{{ jdk_version }}/jetty.xml", dest: '/opt/jetty/etc/jetty.xml' }
  tags: jetty

- name: "Stop jetty after an upgrade"
  command: "/etc/init.d/jetty stop" 
  when:
   - jetty_src.changed
  tags: jetty

- name: "Start jetty by re-reading configs"
  systemd: 
   name: "jetty"
   daemon_reload: True
   state: started
   enabled: True
  tags: jetty
