<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataIDProviders = array (
  'https://shibidp.unipr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://shibidp.unipr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Parma',
    'it' => 
    array (
      'Name' => 'Università di Parma',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.unimore.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.unimore.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Modena e Reggio Emilia',
    'it' => 
    array (
      'Name' => 'Università di Modena e Reggio Emilia',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://ip1.rettorato.unito.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://ip1.rettorato.unito.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Torino',
    'it' => 
    array (
      'Name' => 'Università di Torino',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://shidp.caspur.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://shidp.caspur.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CASPUR',
    'it' => 
    array (
      'Name' => 'CASPUR',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp2.cilea.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp2.cilea.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CILEA',
    'it' => 
    array (
      'Name' => 'CILEA',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.uniroma3.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.uniroma3.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Roma TRE',
    'it' => 
    array (
      'Name' => 'Università di Roma TRE',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://biblio.bo.cnr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://biblio.bo.cnr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CNR Area della Ricerca di Bologna',
    'it' => 
    array (
      'Name' => 'CNR Area della Ricerca di Bologna',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://shibidp.cca.unipd.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://shibidp.cca.unipd.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Padova',
    'it' => 
    array (
      'Name' => 'Università di Padova',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.ba.cnr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.ba.cnr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CNR Area della Ricerca di Bari',
    'it' => 
    array (
      'Name' => 'CNR Area della Ricerca di Bari',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://shibidp.to.cnr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://shibidp.to.cnr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CNR Istituto di Virologia Vegetale',
    'it' => 
    array (
      'Name' => 'CNR Istituto di Virologia Vegetale',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://shib2.to.cnr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://shib2.to.cnr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CNR Ceris',
    'it' => 
    array (
      'Name' => 'CNR Ceris',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://identity.istat.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://identity.istat.it/idp/profile/Shibboleth/SSO',
    'Name' => 'ISTAT',
    'it' => 
    array (
      'Name' => 'ISTAT',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idea.ifc.cnr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idea.ifc.cnr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CNR Istituto di Fisiologia Clinica',
    'it' => 
    array (
      'Name' => 'CNR Istituto di Fisiologia Clinica',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.dir.garr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.dir.garr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'GARR IdP',
    'en' => 
    array (
      'Name' => 'GARR IdP',
    ),
    'it' => 
    array (
      'Name' => 'GARR IdP',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.unica.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.unica.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Cagliari',
    'it' => 
    array (
      'Name' => 'Università di Cagliari',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.uniurb.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.uniurb.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Urbino',
    'it' => 
    array (
      'Name' => 'Università di Urbino',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://identity.unife.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://identity.unife.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Ferrara',
    'it' => 
    array (
      'Name' => 'Università di Ferrara',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.unipv.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.unipv.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Pavia',
    'it' => 
    array (
      'Name' => 'Università di Pavia',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.cnr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.cnr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CNR',
    'it' => 
    array (
      'Name' => 'CNR',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.iit.cnr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.iit.cnr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CNR Istituto di Informatica e Telematica',
    'it' => 
    array (
      'Name' => 'CNR Istituto di Informatica e Telematica',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.iuav.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.iuav.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università IUAV di Venezia',
    'it' => 
    array (
      'Name' => 'Università IUAV di Venezia',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol',
  ),
  'https://shibidp.uniba.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://shibidp.uniba.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Bari',
    'it' => 
    array (
      'Name' => 'Università di Bari',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idem.univpm.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idem.univpm.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università Politecnica delle Marche',
    'it' => 
    array (
      'Name' => 'Università Politecnica delle Marche',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.unimib.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.unimib.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Milano Bicocca',
    'it' => 
    array (
      'Name' => 'Università di Milano Bicocca',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.unive.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.unive.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università Ca Foscari di Venezia',
    'it' => 
    array (
      'Name' => 'Università Ca Foscari di Venezia',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'http://idp.unibo.it/adfs/services/trust' => 
  array (
    'SSO' => 'https://idp.unibo.it/adfs/ls/',
    'Name' => 'Università di Bologna',
    'it-IT' => 
    array (
      'Name' => 'Università di Bologna',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idem-idp.ilc.cnr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idem-idp.ilc.cnr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CNR Istituto di Linguistica Computazionale',
    'it' => 
    array (
      'Name' => 'CNR Istituto di Linguistica Computazionale',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.unitn.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.unitn.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Trento',
    'it' => 
    array (
      'Name' => 'Università di Trento',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp2.idem.garr.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp2.idem.garr.it/idp/profile/Shibboleth/SSO',
    'Name' => 'GARR FI idp215',
    'it' => 
    array (
      'Name' => 'GARR FI idp215',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idemshibb.unina.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idemshibb.unina.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Napoli Federico II',
    'it' => 
    array (
      'Name' => 'Università di Napoli Federico II',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.uniparthenope.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.uniparthenope.it/idp/profile/Shibboleth/SSO',
    'Name' => 'UniPARTHENOPE IdP',
    'en' => 
    array (
      'Name' => 'UniPARTHENOPE IdP',
    ),
    'it' => 
    array (
      'Name' => 'UniPARTHENOPE IdP',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idem.ced.inaf.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idem.ced.inaf.it/idp/profile/Shibboleth/SSO',
    'Name' => 'INAF',
    'it' => 
    array (
      'Name' => 'INAF',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://shibidp.polimi.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://shibidp.polimi.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Politecnico di Milano',
    'it' => 
    array (
      'Name' => 'Politecnico di Milano',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://shibboleth.unifi.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://shibboleth.unifi.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Firenze',
    'it' => 
    array (
      'Name' => 'Università di Firenze',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idem.unina2.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idem.unina2.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Seconda Università di Napoli',
    'it' => 
    array (
      'Name' => 'Seconda Università di Napoli',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp-staf-prod.cineca.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp-is.cineca.it/idp/profile/Shibboleth/SSO',
    'Name' => 'CINECA',
    'it' => 
    array (
      'Name' => 'CINECA',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idem.unisalento.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idem.unisalento.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università del Salento',
    'it' => 
    array (
      'Name' => 'Università del Salento',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idemfero.units.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idemfero.units.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Trieste',
    'it' => 
    array (
      'Name' => 'Università di Trieste',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.unipi.it/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.unipi.it/idp/profile/Shibboleth/SSO',
    'Name' => 'Università di Pisa',
    'it' => 
    array (
      'Name' => 'Università di Pisa',
    ),
    'Protocols' => 'urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://idp.infn.it/saml2/idp/metadata.php' => 
  array (
    'SSO' => 'https://idp.infn.it/shib13/idp/SSOService.php',
    'Name' => 'Istituto Nazionale di Fisica Nucleare',
    'en' => 
    array (
      'Name' => 'Istituto Nazionale di Fisica Nucleare',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0',
  ),
)
?>