<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataSProviders = array (
  'https://fire.rettorato.unito.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://www.serviziweb.unito.it/youblog/Shibboleth.sso/DS',
    ),
    'Name' => 'YouBlog',
    'en' => 
    array (
      'Name' => 'YouBlog',
    ),
    'it' => 
    array (
      'Name' => 'YouBlog',
    ),
    'ACURL' => 
    array (
      0 => 'https://www.serviziweb.unito.it/youblog/Shibboleth.sso/SAML/Artifact',
      1 => 'https://www.serviziweb.unito.it/youblog/Shibboleth.sso/SAML/POST',
      2 => 'https://www.serviziweb.unito.it/youblog/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://www.serviziweb.unito.it/youblog/Shibboleth.sso/SAML2/ECP',
      4 => 'https://www.serviziweb.unito.it/youblog/Shibboleth.sso/SAML2/POST',
      5 => 'https://www.serviziweb.unito.it/youblog/Shibboleth.sso/SAML2/POST-SimpleSign',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://vconf.garr.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://vconf.garr.it/Shibboleth.sso/DS',
    ),
    'Name' => 'https://vconf.garr.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://vconf.garr.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://vconf.garr.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://vconf.garr.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://vconf.garr.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://vconf.garr.it/Shibboleth.sso/SAML/POST',
      5 => 'https://vconf.garr.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://vconf-dev.cineca.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://vconf-dev.cineca.it/Shibboleth.sso/DS',
      1 => 'http://vconf-dev.cineca.it/Shibboleth.sso/DS',
    ),
    'Name' => 'https://vconf-dev.cineca.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://vconf-dev.cineca.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://vconf-dev.cineca.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://vconf-dev.cineca.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://vconf-dev.cineca.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://vconf-dev.cineca.it/Shibboleth.sso/SAML/POST',
      5 => 'https://vconf-dev.cineca.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://aai.caspur.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://aai.caspur.it/Shibboleth.sso/WAYF/',
    ),
    'Name' => 'https://aai.caspur.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://aai.caspur.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://aai.caspur.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://aai.caspur.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://aai.caspur.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://aai.caspur.it/Shibboleth.sso/SAML/POST',
      5 => 'https://aai.caspur.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'http://shibboleth.metapress.com/shibboleth-sp' => 
  array (
    'Name' => 'http://shibboleth.metapress.com/shibboleth-sp',
    'ACURL' => 
    array (
      0 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML2/POST',
      1 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML2/ECP',
      4 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML/POST',
      5 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://scauth.scopus.com/' => 
  array (
    'Name' => 'https://scauth.scopus.com/',
    'ACURL' => 
    array (
      0 => 'https://scauth.scopus.com/SHIRE/SAML/POST',
      1 => 'https://cdc315-scauth.scopus.com/SHIRE/SAML/POST',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol',
  ),
  'https://sdauth.sciencedirect.com/' => 
  array (
    'Name' => 'https://sdauth.sciencedirect.com/',
    'ACURL' => 
    array (
      0 => 'https://sdauth.sciencedirect.com/SHIRE/SAML/POST',
      1 => 'https://cdc315-sdauth.sciencedirect.com/SHIRE/SAML/POST',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol',
  ),
  'https://atlases.muni.cz/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://atlases.muni.cz/Shibboleth.sso/WAYF/eduid',
      1 => 'https://atlases.muni.cz/Shibboleth.sso/DS',
      2 => 'https://atlases.muni.cz/Shibboleth.sso/DS/eduid',
      3 => 'https://atlases.muni.cz/Shibboleth.sso/DS/dfnaai',
      4 => 'https://atlases.muni.cz/Shibboleth.sso/idemgarr',
      5 => 'https://atlases.muni.cz/Shibboleth.sso/surf',
      6 => 'https://atlases.muni.cz/Shibboleth.sso/niif',
      7 => 'https://atlases.muni.cz/Shibboleth.sso/upki',
      8 => 'https://atlases.muni.cz/Shibboleth.sso/chimarrao',
      9 => 'https://atlases.muni.cz/Shibboleth.sso/aaf',
      10 => 'https://atlases.muni.cz/Shibboleth.sso/pionier',
      11 => 'https://atlases.muni.cz/Shibboleth.sso/kalmar',
      12 => 'https://atlases.muni.cz/Shibboleth.sso/arnes',
      13 => 'https://atlases.muni.cz/Shibboleth.sso/switch',
    ),
    'Name' => 'https://atlases.muni.cz/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://atlases.muni.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://atlases.muni.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://atlases.muni.cz/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://atlases.muni.cz/Shibboleth.sso/SAML2/ECP',
      4 => 'https://atlases.muni.cz/Shibboleth.sso/SAML/POST',
      5 => 'https://atlases.muni.cz/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://sp.tshhosting.com/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://www.isiknowledge.com/',
      1 => 'https://www.webofknowledge.com/',
      2 => 'https://www.webofknowledgev4.com/',
    ),
    'Name' => 'https://sp.tshhosting.com/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://www.isiknowledge.com/?auth=Shibboleth',
      1 => 'https://www.webofknowledge.com/?auth=Shibboleth',
      2 => 'https://www.isiknowledge.com/?auth=Shibboleth',
      3 => 'https://www.webofknowledge.com/?auth=Shibboleth',
      4 => 'https://www.webofknowledgev4.com/?auth=Shibboleth',
      5 => 'https://www.webofknowledgev4.com/?auth=Shibboleth',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol',
  ),
  'https://wifiauth1.unito.it/shibboleth' => 
  array (
    'Name' => 'https://wifiauth1.unito.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://wifiauth1.unito.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://wifiauth1.unito.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://wifiauth1.unito.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://wifiauth1.unito.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://wifiauth1.unito.it/Shibboleth.sso/SAML/POST',
      5 => 'https://wifiauth1.unito.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://idem-wifi.unito.it/shibboleth' => 
  array (
    'Name' => 'https://idem-wifi.unito.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://idem-wifi.unito.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://idem-wifi.unito.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://idem-wifi.unito.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://idem-wifi.unito.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://idem-wifi.unito.it/Shibboleth.sso/SAML/POST',
      5 => 'https://idem-wifi.unito.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'http://sdos.cilea.it' => 
  array (
    'Name' => 'CILEA SDoS',
    'it' => 
    array (
      'Name' => 'CILEA SDoS',
    ),
    'ACURL' => 
    array (
      0 => 'https://sdos.cilea.it/Shibboleth.sso/SAML/POST',
      1 => 'https://sdos.cilea.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://nildeutenti.bo.cnr.it/sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://nildeutenti.bo.cnr.it/Shibboleth.sso/WAYF/IDEM',
    ),
    'Name' => 'https://nildeutenti.bo.cnr.it/sp',
    'ACURL' => 
    array (
      0 => 'https://nildeutenti.bo.cnr.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://nildeutenti.bo.cnr.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://nildeutenti.bo.cnr.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://nildeutenti.bo.cnr.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://nildeutenti.bo.cnr.it/Shibboleth.sso/SAML/POST',
      5 => 'https://nildeutenti.bo.cnr.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://moodle-shib.unimore.it/sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://moodle-shib.unimore.it/Shibboleth.sso/WAYF/IDEM',
    ),
    'Name' => 'https://moodle-shib.unimore.it/sp',
    'ACURL' => 
    array (
      0 => 'https://moodle-shib.unimore.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://moodle-shib.unimore.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://moodle-shib.unimore.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://moodle-shib.unimore.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://moodle-shib.unimore.it/Shibboleth.sso/SAML/POST',
      5 => 'https://moodle-shib.unimore.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://sp2-test.garr.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://sp2-test.garr.it/Shibboleth.sso/WAYF',
    ),
    'Name' => 'SP TEST sp2 Firenze',
    'it' => 
    array (
      'Name' => 'SP TEST sp2 Firenze',
    ),
    'ACURL' => 
    array (
      0 => 'https://sp2-test.garr.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://sp2-test.garr.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://sp2-test.garr.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://sp2-test.garr.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://sp2-test.garr.it/Shibboleth.sso/SAML/POST',
      5 => 'https://sp2-test.garr.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://captiveportal.caspur.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://captiveportal.caspur.it/Shibboleth.sso/DS',
    ),
    'Name' => 'https://captiveportal.caspur.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://captiveportal.caspur.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://captiveportal.caspur.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://captiveportal.caspur.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://captiveportal.caspur.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://captiveportal.caspur.it/Shibboleth.sso/SAML/POST',
      5 => 'https://captiveportal.caspur.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://periodici.caspur.it/shibboleth' => 
  array (
    'Name' => 'https://periodici.caspur.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://periodici.caspur.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://periodici.caspur.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://periodici.caspur.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://periodici.caspur.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://periodici.caspur.it/Shibboleth.sso/SAML/POST',
      5 => 'https://periodici.caspur.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://wireless.unife.it/idem' => 
  array (
    'Name' => 'https://wireless.unife.it/idem',
    'ACURL' => 
    array (
      0 => 'https://wireless.unife.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://wireless.unife.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://wireless.unife.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://wireless.unife.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://wireless.unife.it/Shibboleth.sso/SAML/POST',
      5 => 'https://wireless.unife.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://server2.to.cnr.it/sp' => 
  array (
    'Name' => 'https://server2.to.cnr.it/sp',
    'ACURL' => 
    array (
      0 => 'https://server2.to.cnr.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://server2.to.cnr.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://server2.to.cnr.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://server2.to.cnr.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://server2.to.cnr.it/Shibboleth.sso/SAML/POST',
      5 => 'https://server2.to.cnr.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://tcs-personal.garr.it/simplesamlphp/module.php/saml/sp/metadata.php/default-sp' => 
  array (
    'Name' => 'https://tcs-personal.garr.it/simplesamlphp/module.php/saml/sp/metadata.php/default-sp',
    'ACURL' => 
    array (
      0 => 'https://tcs-personal.garr.it/simplesamlphp/module.php/saml/sp/saml2-acs.php/default-sp',
      1 => 'https://tcs-personal.garr.it/simplesamlphp/module.php/saml/sp/saml1-acs.php/default-sp',
      2 => 'https://tcs-personal.garr.it/simplesamlphp/module.php/saml/sp/saml2-acs.php/default-sp',
      3 => 'https://tcs-personal.garr.it/simplesamlphp/module.php/saml/sp/saml1-acs.php/default-sp/artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://tcs-escience.garr.it/simplesamlphp/module.php/saml/sp/metadata.php/default-sp' => 
  array (
    'Name' => 'https://tcs-escience.garr.it/simplesamlphp/module.php/saml/sp/metadata.php/default-sp',
    'ACURL' => 
    array (
      0 => 'https://tcs-escience.garr.it/simplesamlphp/module.php/saml/sp/saml2-acs.php/default-sp',
      1 => 'https://tcs-escience.garr.it/simplesamlphp/module.php/saml/sp/saml1-acs.php/default-sp',
      2 => 'https://tcs-escience.garr.it/simplesamlphp/module.php/saml/sp/saml2-acs.php/default-sp',
      3 => 'https://tcs-escience.garr.it/simplesamlphp/module.php/saml/sp/saml1-acs.php/default-sp/artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://ieeexplore.ieee.org/shibboleth-sp' => 
  array (
    'Name' => 'https://ieeexplore.ieee.org/shibboleth-sp',
    'ACURL' => 
    array (
      0 => 'https://ieeexplore.ieee.org/Shibboleth/Shibboleth.sso/SAML2/POST',
      1 => 'https://ieeexplore.ieee.org/Shibboleth/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://ieeexplore.ieee.org/Shibboleth/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://ieeexplore.ieee.org/Shibboleth/Shibboleth.sso/SAML/POST',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://xploreuat.ieee.org/shibboleth-sp' => 
  array (
    'Name' => 'https://xploreuat.ieee.org/shibboleth-sp',
    'ACURL' => 
    array (
      0 => 'https://xploreuat.ieee.org/Shibboleth/Shibboleth.sso/SAML2/POST',
      1 => 'https://xploreuat.ieee.org/Shibboleth/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://xploreuat.ieee.org/Shibboleth/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://xploreuat.ieee.org/Shibboleth/Shibboleth.sso/SAML/POST',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://wlcradius1.pi.cnr.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://wlcradius1.pi.cnr.it/Shibboleth.sso/DS',
    ),
    'Name' => 'https://wlcradius1.pi.cnr.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://wlcradius1.pi.cnr.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://wlcradius1.pi.cnr.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://wlcradius1.pi.cnr.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://wlcradius1.pi.cnr.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://wlcradius1.pi.cnr.it/Shibboleth.sso/SAML/POST',
      5 => 'https://wlcradius1.pi.cnr.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://www.nejm.org/shibboleth' => 
  array (
    'Name' => 'https://www.nejm.org/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://www.nejm.org/action/samlACS',
      1 => 'https://www.nejm.org/action/samlACS',
      2 => 'https://www.nejm.org/action/samlACS',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://www.annualreviews.org/shibboleth' => 
  array (
    'Name' => 'https://www.annualreviews.org/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://www.annualreviews.org/action/samlACS',
      1 => 'https://www.annualreviews.org/action/samlACS',
      2 => 'https://www.annualreviews.org/action/samlACS',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://rwt.refworks.com/shibboleth/testshib/sp' => 
  array (
    'Name' => 'https://rwt.refworks.com/shibboleth/testshib/sp',
    'ACURL' => 
    array (
      0 => 'https://rwt.refworks.com/Shibboleth.sso/SAML2/POST',
      1 => 'https://rwt.refworks.com/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://rwt.refworks.com/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://rwt.refworks.com/Shibboleth.sso/SAML2/ECP',
      4 => 'https://rwt.refworks.com/Shibboleth.sso/SAML/POST',
      5 => 'https://rwt.refworks.com/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://www.refworks.com/shibboleth/sp' => 
  array (
    'Name' => 'https://www.refworks.com/shibboleth/sp',
    'ACURL' => 
    array (
      0 => 'https://www.refworks.com/Shibboleth.sso/SAML2/POST',
      1 => 'https://www.refworks.com/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://www.refworks.com/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://www.refworks.com/Shibboleth.sso/SAML2/ECP',
      4 => 'https://www.refworks.com/Shibboleth.sso/SAML/POST',
      5 => 'https://www.refworks.com/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://fire.rettorato.unito.it/shibboleth/bottaerisposta' => 
  array (
    'Name' => 'https://fire.rettorato.unito.it/shibboleth/bottaerisposta',
    'ACURL' => 
    array (
      0 => 'https://www.serviziweb.unito.it/bottaerisposta/shib-idem/Shibboleth.sso/SAML/Artifact',
      1 => 'https://www.serviziweb.unito.it/bottaerisposta/shib-idem/Shibboleth.sso/SAML/POST',
      2 => 'https://www.serviziweb.unito.it/bottaerisposta/shib-idem/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://www.serviziweb.unito.it/bottaerisposta/shib-idem/Shibboleth.sso/SAML2/ECP',
      4 => 'https://www.serviziweb.unito.it/bottaerisposta/shib-idem/Shibboleth.sso/SAML2/POST',
      5 => 'https://www.serviziweb.unito.it/bottaerisposta/shib-idem/Shibboleth.sso/SAML2/POST-SimpleSign',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://radius.uniurb.it/shibboleth' => 
  array (
    'Name' => 'https://radius.uniurb.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://radius.uniurb.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://radius.uniurb.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://radius.uniurb.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://radius.uniurb.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://radius.uniurb.it/Shibboleth.sso/SAML/POST',
      5 => 'https://radius.uniurb.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://foodl.org/simplesaml/module.php/saml/sp/metadata.php/saml' => 
  array (
    'Name' => 'https://foodl.org/simplesaml/module.php/saml/sp/metadata.php/saml',
    'ACURL' => 
    array (
      0 => 'https://foodl.org/simplesaml/module.php/saml/sp/saml2-acs.php/saml',
      1 => 'https://foodl.org/simplesaml/module.php/saml/sp/saml1-acs.php/saml',
      2 => 'https://foodl.org/simplesaml/module.php/saml/sp/saml2-acs.php/saml',
      3 => 'https://foodl.org/simplesaml/module.php/saml/sp/saml1-acs.php/saml/artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://www.idem.garr.it/components/com_idemauth/simplesamlphp/www/module.php/saml/sp/metadata.php/idemauth-sp' => 
  array (
    'Name' => 'https://www.idem.garr.it/components/com_idemauth/simplesamlphp/www/module.php/saml/sp/metadata.php/idemauth-sp',
    'ACURL' => 
    array (
      0 => 'https://www.idem.garr.it/components/com_idemauth/simplesamlphp/www/module.php/saml/sp/saml2-acs.php/idemauth-sp',
      1 => 'https://www.idem.garr.it/components/com_idemauth/simplesamlphp/www/module.php/saml/sp/saml1-acs.php/idemauth-sp',
      2 => 'https://www.idem.garr.it/components/com_idemauth/simplesamlphp/www/module.php/saml/sp/saml2-acs.php/idemauth-sp',
      3 => 'https://www.idem.garr.it/components/com_idemauth/simplesamlphp/www/module.php/saml/sp/saml1-acs.php/idemauth-sp/artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://wifi.pd.cnr.it/IDEMauth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://wifi.pd.cnr.it/Shibboleth.sso/WAYF',
    ),
    'Name' => 'https://wifi.pd.cnr.it/IDEMauth',
    'ACURL' => 
    array (
      0 => 'https://wifi.pd.cnr.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://wifi.pd.cnr.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://wifi.pd.cnr.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://wifi.pd.cnr.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://wifi.pd.cnr.it/Shibboleth.sso/SAML/POST',
      5 => 'https://wifi.pd.cnr.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://shibboleth.ovid.com/entity' => 
  array (
    'Name' => 'https://shibboleth.ovid.com/entity',
    'ACURL' => 
    array (
      0 => 'https://shibboleth-dev.ovid.com:8085/Shibboleth.sso/SAML/POST',
      1 => 'https://shibboleth-dev.ovid.com:8085/Shibboleth.sso/SAML/Artifact',
      2 => 'https://shib-qa.ovid.com/Shibboleth.sso/SAML/POST',
      3 => 'https://shibboleth.ovid.com/Shibboleth.sso/SAML/POST',
      4 => 'https://shib-qa.ovid.com/Shibboleth.sso/SAML/Artifact',
      5 => 'https://shibboleth.ovid.com/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol',
  ),
  'https://terena.org/sp' => 
  array (
    'Name' => 'https://terena.org/sp',
    'ACURL' => 
    array (
      0 => 'https://login.terena.org/wayf/module.php/saml/sp/saml2-acs.php/default-sp',
      1 => 'https://login.terena.org/wayf/module.php/saml/sp/saml1-acs.php/default-sp',
      2 => 'https://login.terena.org/wayf/module.php/saml/sp/saml2-acs.php/default-sp',
      3 => 'https://login.terena.org/wayf/module.php/saml/sp/saml1-acs.php/default-sp/artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://captive.wifi.polimi.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://captive.wifi.polimi.it/Shibboleth.sso/Login',
    ),
    'Name' => 'https://captive.wifi.polimi.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://captive.wifi.polimi.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://captive.wifi.polimi.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://captive.wifi.polimi.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://captive.wifi.polimi.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://captive.wifi.polimi.it/Shibboleth.sso/SAML/POST',
      5 => 'https://captive.wifi.polimi.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://mediarepository.units.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'http://mediarepository.units.it/Shibboleth.sso/DS',
    ),
    'Name' => 'https://mediarepository.units.it/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://mediarepository.units.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://mediarepository.units.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://mediarepository.units.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://mediarepository.units.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://mediarepository.units.it/Shibboleth.sso/SAML/POST',
      5 => 'https://mediarepository.units.it/Shibboleth.sso/SAML/Artifact',
      6 => 'https://moodle2.units.it/Shibboleth.sso/SAML2/POST',
      7 => 'https://moodle2.units.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      8 => 'https://moodle2.units.it/Shibboleth.sso/SAML2/Artifact',
      9 => 'https://moodle2.units.it/Shibboleth.sso/SAML2/ECP',
      10 => 'https://moodle2.units.it/Shibboleth.sso/SAML/POST',
      11 => 'https://moodle2.units.it/Shibboleth.sso/SAML/Artifact',
      12 => 'https://media.units.it/Shibboleth.sso/SAML2/POST',
      13 => 'https://media.units.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      14 => 'https://media.units.it/Shibboleth.sso/SAML2/Artifact',
      15 => 'https://media.units.it/Shibboleth.sso/SAML2/ECP',
      16 => 'https://media.units.it/Shibboleth.sso/SAML/POST',
      17 => 'https://media.units.it/Shibboleth.sso/SAML/Artifact',
      18 => 'https://mooshib.units.it/Shibboleth.sso/SAML2/POST',
      19 => 'https://mooshib.units.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      20 => 'https://mooshib.units.it/Shibboleth.sso/SAML2/Artifact',
      21 => 'https://mooshib.units.it/Shibboleth.sso/SAML2/ECP',
      22 => 'https://mooshib.units.it/Shibboleth.sso/SAML/POST',
      23 => 'https://mooshib.units.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://applications.eu-decide.eu/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://applications.eu-decide.eu/Shibboleth.sso/DS',
    ),
    'Name' => 'DECIDE Science Gateway',
    'en' => 
    array (
      'Name' => 'DECIDE Science Gateway',
    ),
    'it' => 
    array (
      'Name' => 'DECIDE Science Gateway',
    ),
    'ACURL' => 
    array (
      0 => 'https://applications.eu-decide.eu/Shibboleth.sso/SAML2/POST',
      1 => 'https://applications.eu-decide.eu/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://applications.eu-decide.eu/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://applications.eu-decide.eu/Shibboleth.sso/SAML2/ECP',
      4 => 'https://applications.eu-decide.eu/Shibboleth.sso/SAML/POST',
      5 => 'https://applications.eu-decide.eu/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://applications.eumedgrid.eu/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://applications.eumedgrid.eu/Shibboleth.sso/DS',
    ),
    'Name' => 'EUMEDGRID Science Gateway',
    'en' => 
    array (
      'Name' => 'EUMEDGRID Science Gateway',
    ),
    'it' => 
    array (
      'Name' => 'EUMEDGRID Science Gateway',
    ),
    'ACURL' => 
    array (
      0 => 'https://applications.eumedgrid.eu/Shibboleth.sso/SAML2/POST',
      1 => 'https://applications.eumedgrid.eu/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://applications.eumedgrid.eu/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://applications.eumedgrid.eu/Shibboleth.sso/SAML2/ECP',
      4 => 'https://applications.eumedgrid.eu/Shibboleth.sso/SAML/POST',
      5 => 'https://applications.eumedgrid.eu/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://gisela-gw.ct.infn.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://gisela-gw.ct.infn.it/Shibboleth.sso/DS',
    ),
    'Name' => 'GISELA Science Gateway',
    'en' => 
    array (
      'Name' => 'GISELA Science Gateway',
    ),
    'it' => 
    array (
      'Name' => 'GISELA Science Gateway',
    ),
    'ACURL' => 
    array (
      0 => 'https://gisela-gw.ct.infn.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://gisela-gw.ct.infn.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://gisela-gw.ct.infn.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://gisela-gw.ct.infn.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://gisela-gw.ct.infn.it/Shibboleth.sso/SAML/POST',
      5 => 'https://gisela-gw.ct.infn.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://indicate-gw.consorzio-cometa.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://indicate-gw.consorzio-cometa.it/Shibboleth.sso/DS',
    ),
    'Name' => 'INDICATE e-Culture Science Gateway',
    'en' => 
    array (
      'Name' => 'INDICATE e-Culture Science Gateway',
    ),
    'it' => 
    array (
      'Name' => 'INDICATE e-Culture Science Gateway',
    ),
    'ACURL' => 
    array (
      0 => 'https://indicate-gw.consorzio-cometa.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://indicate-gw.consorzio-cometa.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://indicate-gw.consorzio-cometa.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://indicate-gw.consorzio-cometa.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://indicate-gw.consorzio-cometa.it/Shibboleth.sso/SAML/POST',
      5 => 'https://indicate-gw.consorzio-cometa.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'https://ricevi.ct.infn.it/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://ricevi.ct.infn.it/Shibboleth.sso/DS',
    ),
    'Name' => 'RICeVI portal',
    'en' => 
    array (
      'Name' => 'RICeVI portal',
    ),
    'it' => 
    array (
      'Name' => 'RICeVI portal',
    ),
    'ACURL' => 
    array (
      0 => 'https://ricevi.ct.infn.it/Shibboleth.sso/SAML2/POST',
      1 => 'https://ricevi.ct.infn.it/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://ricevi.ct.infn.it/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://ricevi.ct.infn.it/Shibboleth.sso/SAML2/ECP',
      4 => 'https://ricevi.ct.infn.it/Shibboleth.sso/SAML/POST',
      5 => 'https://ricevi.ct.infn.it/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
  'http://shibboleth.ebscohost.com' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://shibboleth.ebscohost.com/Shibboleth.sso/Login',
    ),
    'Name' => 'http://shibboleth.ebscohost.com',
    'ACURL' => 
    array (
      0 => 'https://shibboleth.ebscohost.com/Shibboleth.sso/SAML/POST',
      1 => 'https://shibboleth.ebscohost.com/Shibboleth.sso/SAML/Artifact',
      2 => 'https://shibboleth.ebscohost.com/Shibboleth.sso/SAML2/POST',
      3 => 'https://shibboleth.ebscohost.com/Shibboleth.sso/SAML2/POST-SimpleSign',
      4 => 'https://shibboleth.ebscohost.com/Shibboleth.sso/SAML2/Artifact',
      5 => 'https://shibboleth.ebscohost.com/Shibboleth.sso/SAML2/ECP',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://wifi-idem.cilea.it/SAML/module.php/saml/sp/metadata.php/default-sp' => 
  array (
    'Name' => 'https://wifi-idem.cilea.it/SAML/module.php/saml/sp/metadata.php/default-sp',
    'ACURL' => 
    array (
      0 => 'https://wifi-idem.cilea.it/SAML/module.php/saml/sp/saml2-acs.php/default-sp',
      1 => 'https://wifi-idem.cilea.it/SAML/module.php/saml/sp/saml1-acs.php/default-sp',
      2 => 'https://wifi-idem.cilea.it/SAML/module.php/saml/sp/saml2-acs.php/default-sp',
      3 => 'https://wifi-idem.cilea.it/SAML/module.php/saml/sp/saml1-acs.php/default-sp/artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'https://zeroshell.uniparthenope.it:12081/shibboleth' => 
  array (
    'Name' => 'https://zeroshell.uniparthenope.it:12081/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://zeroshell.uniparthenope.it:12081/Shibboleth.sso/SAML2/POST',
      1 => 'https://zeroshell.uniparthenope.it:12081/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://zeroshell.uniparthenope.it:12081/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://zeroshell.uniparthenope.it:12081/Shibboleth.sso/SAML2/ECP',
      4 => 'https://zeroshell.uniparthenope.it:12081/Shibboleth.sso/SAML/POST',
      5 => 'https://zeroshell.uniparthenope.it:12081/Shibboleth.sso/SAML/Artifact',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol',
  ),
)
?>
