---
# tasks file for check_mk
- name: "Include OS-specific variables."
  include_vars: "{{ ansible_os_family }}.yml"
  tags: check_mk_agent

- name: "Install Check_MK"
  import_tasks: check_mk_agent-install.yml
  when: check_mk is defined
  tags: check_mk_agent

- name: "Configure Check_MK"
  import_tasks: check_mk_agent-configure.yml
  when: check_mk is defined
  tags: check_mk_agent
