---
# Install OpenJDK on Debian

- name: "Run 'apt-get update' if the last one is more than 3600 seconds ago"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Install OpenJDK"
  apt:
   name: ['ca-certificates-java', 'default-jre-headless', 'default-jdk-headless']
   state: latest
   install_recommends: no
