---
# defaults file for idp

idp_dl_url: "https://shibboleth.net/downloads/identity-provider/archive/{{ shib_idp_version }}/shibboleth-identity-provider-{{ shib_idp_version }}.tar.gz"

# Shibboleth 4.0.1
#shib_idp_version: "4.0.1"
#shib_idp_checksum: "832f73568c5b74a616332258fd9dc555bb20d7dd9056c18dc0ccf52e9292102a"

# Shibboleth 4.1.0
#shib_idp_version: "4.1.0"
#shib_idp_checksum: "46fe154859f9f1557acd1ae26ee9ac82ded938af52a7dec0b18adbf5bb4510e9"

# Shibboleth 4.1.2
#shib_idp_version: "4.1.2"
#shib_idp_checksum: "2d35dbccc6c6ae6f7eec4adc98eaa406c33df3ad49879839a3839dbf427afff8"

# Shibboleth 4.1.4
shib_idp_version: "4.1.4"
shib_idp_checksum: "65429f547a7854b30713d86ba5901ca718eae91efb3e618ee11108be59bf8a29"

# Available:
#
# OpenJDK: 
#   jdk_type: "openjdk"
#   jdk_version: "11"
#
# Amazon Corretto JDK: 
#   jdk_type: "corretto"
#   jdk_version: "11"

jdk_type: "corretto"
jdk_version: "11"

### Machine Variables:
fqdn: "idp.example.org"
files_dir: "/opt/ansible-shibboleth/inventories/files"

url_password_reset: "https://{{ fqdn }}/flup"

idp_login_default:
 aup:
  en:
   aupUrl: "https://www.garr.it/en/acceptable-use-policies"
  it:
   aupUrl: "https://www.garr.it/it/regole-di-utilizzo-della-rete-aup"

idp_metadata:
 en:
  mdui_displayName: "ENG IdP DisplayName"
  mdui_description: "ENG IdP Description"
  mdui_infoUrl: "https://{{ fqdn }}/en/info.html"
  mdui_privacyUrl: "https://{{ fqdn }}/en/privacy.html"
  mdui_favicon: "https://{{ fqdn }}/en/favicon.png"
  mdui_logo: "https://{{ fqdn }}/en/logo.png"
  org_name: "ENG Organization Name"
  org_displayName: "ENG Organization DisplayName"
  org_url: "https://www.organization.org/en"
 it:
  mdui_displayName: "ITA IdP DisplayName"
  mdui_description: "ITA IdP Description"
  mdui_infoUrl: "https://{{ fqdn }}/it/info.html"
  mdui_privacyUrl: "https://{{ fqdn }}/it/privacy.html"
  mdui_favicon: "https://{{ fqdn }}/it/favicon.png"
  mdui_logo: "https://{{ fqdn }}/it/logo.png"
  org_name: "ITA Organization Name"
  org_displayName: "ITA Organization DisplayName"
  org_url: "https://www.organization.org/it"

idp_contacts:
 technical:
  givenName: "Example Technical"
  surName: "User"
  mail: "technical.user@example.org"
 support:
  givenName: "Example Support"
  surName: "User"
  mail: "support.user@example.org"
  address: "Example Address 32, Milan, Italy"
  telephone: "+393249582321"

idp_db_restore: "false"
idp_sealer_restore: "false"
idp_stats_restore: "false"
